"""TBA"""
glUniform1i = "int"
glUniform2i = "ivec2"
glUniform3i = "ivec3"
glUniform4i = "ivec4"
glUniform1f = "float"
glUniform2f = "vec2"
glUniform3f = "vec3"
glUniform4f = "vec4"
glUniformMatrix2fv = "mat2"
glUniformMatrix3fv = "mat3"
glUniformMatrix4fv = "mat4"
glTexture2D = "sampler2D"
glTexture2DArray = "sampler2DArray"
glTexture3D = "sampler3D"
glTextureCubemap = "samplerCube"
glTexture1D = "sampler1D"
